include:
  - ./docker-compose.ch.yml

services:
  dataset-loader:
    build:
      context: ./dataset_loader
    container_name: dataset-loader
    restart: "no"
    depends_on:
      clickhouse-init:
        condition: service_completed_successfully
    environment:
      RECORDS_COUNT: 10000000
      BATCH_SIZE: 5000
      SKIP_IF_POPULATED: "true"
      CLICKHOUSE_HOST: clickhouse-node1
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin_password
      CLICKHOUSE_DATABASE: default
      CLICKHOUSE_TABLE: events
      CLICKHOUSE_INITIAL_TABLE: initial_events
      CLICKHOUSE_LOCAL_TABLE: events_local
      CLICKHOUSE_INITIAL_LOCAL_TABLE: initial_events_local
      CLICKHOUSE_CLUSTER: ugc_cluster
    command: ["python", "-m", "app.main"]
    networks:
      - clickhouse_net

  wr-profiler:
    build:
      context: ./profiler
    container_name: wr-profiler
    restart: "no"
    depends_on:
      clickhouse-init:
        condition: service_completed_successfully
      dataset-loader:
        condition: service_completed_successfully
    environment:
      CLICKHOUSE_HOST: clickhouse-node1
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin_password
      CLICKHOUSE_DATABASE: default
      CLICKHOUSE_TABLE: events
      CLICKHOUSE_INITIAL_TABLE: initial_events
      CLICKHOUSE_LOCAL_TABLE: events_local
      CLICKHOUSE_INITIAL_LOCAL_TABLE: initial_events_local
      CLICKHOUSE_CLUSTER: ugc_cluster
      WR_DURATION_SECONDS: 30
      WR_INSERT_BATCH_SIZE_LIST: "[1000, 2000, 3000, 5000, 8000]"
      WR_WRITER_THREAD_LIST: "[1,2,3,4,5]"
      WR_READER_THREADS: 10
      WR_MAX_RETRIES: 3
      WR_INSERT_REQUEST_TIMEOUT_SECONDS: 10
      WR_READ_REQUEST_TIMEOUT_SECONDS: 20
      RESULTS_DIR: /results
      CLICKHOUSE_NODE_COUNT: ${CLICKHOUSE_NODE_COUNT:-4}
      CLICKHOUSE_NODE_CPUS: ${CLICKHOUSE_NODE_CPUS:-2}
      CLICKHOUSE_NODE_RAM_GB: ${CLICKHOUSE_NODE_RAM_GB:-2}
      PROFILER_WARMUP_ENABLED: true
      PROFILER_WARMUP_DURATION_SECONDS: 15
    volumes:
      - ./results:/results
    command:
      [
        "python",
        "-m",
        "app.main",
        "run",
        "write_read",
      ]
    networks:
      - clickhouse_net
